/* eslint-disable import/prefer-default-export */

export const MAIN_NAME_UPDATE = 'MAIN_NAME_UPDATE';
export const SET_USER_SUBSCRIPTIONS = 'SET_USER_SUBSCRIPTIONS';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';
export const CHOOSE_LOCATION = 'CHOOSE_LOCATION';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const SET_AUTH_LINK = 'SET_AUTH_LINK';
export const SET_HALLS = 'SET_HALLS';
export const SET_HALLS_TO_PLACES = 'SET_HALLS_TO_PLACES';
export const SET_PLACES = 'SET_PLACES';
export const ADD_HALL = 'ADD_HALL';
export const DELETE_HALL = 'DELETE_HALL';
export const ADD_PLACE = 'ADD_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';
export const EDIT_PLACE = 'EDIT_PLACE';
export const SET_MENU_DEPARTMENTS = 'SET_MENU_DEPARTMENTS';
export const ADD_MENU_DEPARTMENT = 'ADD_MENU_DEPARTMENT';
export const DELETE_MENU_DEPARTMENT = 'DELETE_MENU_DEPARTMENT';
export const EDIT_MENU_DEPARTMENT = 'EDIT_MENU_DEPARTMENT';
export const SET_MENU_CATEGORIES = 'SET_MENU_CATEGORIES';
export const ADD_MENU_CATEGORY = 'ADD_MENU_CATEGORY';
export const DELETE_MENU_CATEGORY = 'DELETE_MENU_CATEGORY';
export const EDIT_MENU_CATEGORY = 'EDIT_MENU_CATEGORY';
export const SET_MENU_ITEMS = 'SET_MENU_ITEMS';
export const ADD_MENU_ITEM = 'ADD_MENU_ITEM';
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM';
export const EDIT_MENU_ITEM = 'EDIT_MENU_ITEM';


export const LOG = 'LOG';
